### ISSUE TITLE
你们的SDK 有些语法错误，请问有专门的工程师维护吗

### ISSUE THREAD

**Issue by Davidzhu001** [TencentCloud/tencentcloud-sdk-ruby#1]
盼星星，盼月亮 RUBY sdk 终于出了。
安耐不住心里的感动，特此感谢一下。

**Comment by zqfan** [comment]
目前只实现了基本功能，后续还会进行完善。
欢迎使用，体验，提出意见。

**Comment by Davidzhu001** [comment]
你们的SDK 有些语法错误，请问有专门的工程师维护吗 #1

**Comment by zqfan** [comment]
@Davidzhu001 有的，请具体指出来，会安排人修复的

**Comment by losingle** [comment]
这个设计和语法真别扭

**Comment by zqfan** [comment]
@losingle 有什么好的项目可以让我们学习下吗？

**Comment by zqfan** [comment]
由于始终没有给出具体的问题，这里先将此单关闭。如果有具体的问题，可以另开新单。

**Comment by nyrf** [comment]
> @losingle 有什么好的项目可以让我们学习下吗？

ruby方法名和变量名用小写下划线的 https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/MethodName

比如
```ruby
def AddSmsTemplate(request)
```

应该写成

```ruby
def add_sms_template(request)
```

可参考：https://github.com/aws/aws-sdk-ruby
