### ISSUE TITLE
`CreateShieldInstance': 不是白名单用户，要在哪里设置白名单用户？

### ISSUE THREAD

**Issue by sugarwyc** [TencentCloud/tencentcloud-sdk-ruby#13]
```
/tencentcloud-sdk-ms-3.0.559/lib/v20180408/client.rb:146:in `CreateShieldInstance': 不是白名单用户。 (TencentCloud::Common::TencentCloudSDKException)
```

**Comment by zqfan** [comment]
请到控制台提工单到ms产品咨询哈，sdk只是对接口的封装，并不清楚产品内部做了什么限制。

**Comment by sugarwyc** [comment]
![iwEcAqNwbmcDAQTRAU4F0QEiBrAh00lwKh66vQRDAUPRAMsAB9IufzhfCAAJomltCgAL0gAAmf8 png_620x10000q90](https://user-images.githubusercontent.com/5518603/235035283-4e91e2b5-d1d3-4a9c-9b8a-ba395ef7a8b6.jpg)

就是免费版不支持，收费的才支持。
