### ISSUE TITLE
能增加 COS 对象存储的 SDK 吗？

### ISSUE THREAD

**Issue by cisolarix** [TencentCloud/tencentcloud-sdk-ruby#14]
RT

**Comment by zqfan** [comment]
这个SDK支持的是腾讯云API3.0的接口，COS产品因为要兼容aws s3协议有提供专门的SDK，可以到官网COS产品文档中找找。

**Comment by killernova** [comment]
> 这个SDK支持的是腾讯云API3.0的接口，COS产品因为要兼容aws s3协议有提供专门的SDK，可以到官网COS产品文档中找找。

官网没有cos Ruby SDK 啊。
