### ISSUE TITLE
麻烦修正 ChargeDetail 参数名字

### ISSUE THREAD

**Issue by fanxy1** [TencentCloud/tencentcloud-sdk-ruby#17]
<img width="1435" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-ruby/assets/26424839/28015dcd-f78d-485c-bd8c-052d2b4a0eee">

**Comment by fanxy1** [comment]
我没有提 pr 的权限

**Comment by fanxy1** [comment]
https://github.com/TencentCloud/tencentcloud-sdk-ruby/pull/18

**Comment by zqfan** [comment]
请问这个是会引起什么问题吗？

**Comment by fanxy1** [comment]
> 请问这个是会引起什么问题吗？

同名参数，ruby 会报错呀

**Comment by zqfan** [comment]
> > 请问这个是会引起什么问题吗？
> 
> 同名参数，ruby 会报错呀

哦，抱歉，我没注意到两个类似的参数。这个数据结构以前有个参数叫Idcard但是被废弃了，新的叫IdCard，看起来是ruby sdk没处理好废弃参数，我看看如何修正。你提交的pr所修改的文件是自动生成的，会在下次更新时覆盖掉
