### ISSUE TITLE
发布到rubygems.org

### ISSUE THREAD

**Issue by kevin-jj** [TencentCloud/tencentcloud-sdk-ruby#4]
非常感谢腾讯云团队做了ruby版的api封装。

有一个建议，是否可以把这个开源项目发布到rubygems.org以便开发者在生产环境快速安装使用。

谢谢

@zqfan @alfredhuang211

**Comment by zqfan** [comment]
感谢关注，可以，有此计划

**Comment by xgrei** [comment]
临时解决方法，比如 `tencentcloud-sdk-common`: 

```ruby
# Gemfile
gem 'tencentcloud-sdk-common', github: 'TencentCloud/tencentcloud-sdk-ruby', glob: 'tencentcloud-sdk-common/tencentcloud-sdk-common.gemspec'
```

**Comment by nyrf** [comment]
+1, 今天看官方有gem，拿来调用sms，然后一直报错，再一看，现在rubygems上的还是1.057, 这滞后太多了，麻烦能不能更新下？我看就发了一版后面就一个没更新了。用github的方式，布署到腾讯云上，安装时又慢的不行

```
gem install tencentcloud-sdk-sms
Successfully installed tencentcloud-sdk-sms-1.0.57
```

**Comment by zqfan** [comment]
> +1, 今天看官方有gem，拿来调用sms，然后一直报错，再一看，现在rubygems上的还是1.057, 这滞后太多了，麻烦能不能更新下？我看就发了一版后面就一个没更新了。用github的方式，布署到腾讯云上，安装时又慢的不行
> 
> ```
> gem install tencentcloud-sdk-sms
> Successfully installed tencentcloud-sdk-sms-1.0.57
> ```

这些并非我们发布的，我刚试了下，因为名字被占用了，是不能直接推的。我还未找到如何取回这些名字的途径

**Comment by nyrf** [comment]
> > +1, 今天看官方有gem，拿来调用sms，然后一直报错，再一看，现在rubygems上的还是1.057, 这滞后太多了，麻烦能不能更新下？我看就发了一版后面就一个没更新了。用github的方式，布署到腾讯云上，安装时又慢的不行
> > ```
> > gem install tencentcloud-sdk-sms
> > Successfully installed tencentcloud-sdk-sms-1.0.57
> > ```
> 
> 这些并非我们发布的，我刚试了下，因为名字被占用了，是不能直接推的。我还未找到如何取回这些名字的途径

我找到发布人的信息，上面有个qq的邮箱，可以联系看看让他让出名字  https://github.com/NaiveCAI

**Comment by nyrf** [comment]
看了下，rubygem上发了几个包，对应找到

tencentcloud-sdk-common 和 tencentcloud-sdk-sms https://github.com/NaiveCAI
tencentcloud-sdk-cvm https://github.com/cpunion

另外tencentcloud-sdk-trtc-1.0.119 和tencentcloud-sdk-common-1.0.119  是加了版本号的，这个没影响

**Comment by zqfan** [comment]
已经给他们邮件了

**Comment by nyrf** [comment]
> 已经给他们邮件了

刚看了下，rubygem上的都已经下了

**Comment by zqfan** [comment]
不行，common和sms只是删除了版本，但是包本身还未删除，发布时报错了
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem. Ask an owner to add you with: gem owner tencentcloud-sdk-common --add tencentcloudapi@tencent.com

**Comment by nyrf** [comment]
> 不行，common和sms只是删除了版本，但是包本身还未删除，发布时报错了
> Pushing gem to https://rubygems.org...
> You do not have permission to push to this gem. Ask an owner to add you with: gem owner tencentcloud-sdk-common --add [tencentcloudapi@tencent.com](mailto:tencentcloudapi@tencent.com)

如果实在没法，那只能联系`support@rubygems.org`看下了

**Comment by zqfan** [comment]
联系了原先的gem owner，目前来看虽然tencentcloud-sdk-ruby这个总包没有拿回来，但是至少每个产品单独的包例如tencentcloud-sdk-common都已经拿回来了，今天会全部更新1.0.200版本，后续会随github源码发布各版本gem。

**Comment by nyrf** [comment]
> 联系了原先的gem owner，目前来看虽然tencentcloud-sdk-ruby这个总包没有拿回来，但是至少每个产品单独的包例如tencentcloud-sdk-common都已经拿回来了，今天会全部更新1.0.200版本，后续会随github源码发布各版本gem。

看到，已经用上，这下方便多了，另外建议方法和参数名能按ruby的风格来写，现在这种java的写法有点别扭。
