### ISSUE TITLE
Signature failed

### ISSUE THREAD

**Issue by microdevil** [TencentCloud/tencentcloud-sdk-ruby#9]
Hi...

I have implemented one of API on this SDK. 

I get this error after several hours

`TencentCloud::Common::TencentCloudSDKException ([TencentCloudSDKError] Code=AuthFailure.SignatureFailure, Message=请求签名验证失败，请检查您的签名计算是否正确。, RequestId=e3be6d37-524b-4f53-a547-a908d032d69a)`

This is my code

`cred = Credential.new('mysecetid', 'mysecretkey')`
`httpProfile 				= HttpProfile.new()`
`httpProfile.endpoint 		= "live.tencentcloudapi.com"`
`clientProfile 				= ClientProfile.new()`
`clientProfile.http_profile 	= httpProfile`
`client 						= Client.new(cred, "", clientProfile)`
`req 						= DescribeLiveStreamStateRequest.new`
`req.AppName 				= "myappname"`
`req.DomainName 				= "mydomainname"`
`req.StreamName 				= streamer_id`
`resp 						= client.DescribeLiveStreamState(req)`
`result 						= JSON.parse(resp.to_json)`

I have been created mysecretid and mysecretkey from API explorer.

Thanks

**Comment by zqfan** [comment]
Generally, sdk signature process is well tested and cannot be wrong. Please check your secretid & secretkey carefully, and make sure there is no space (or other blank characters) before/behind it.

secretkey is very important, DO NOT leak it to anyone.

**Comment by microdevil** [comment]
Hi @zqfan 

There was no issue with my secretid and secret key. For my first implementation, it was running well. However, after several hours, I get errors when I run the code that is never changed by me. But, after several minutes, it is running well again without a change in my code

Thanks

**Comment by zqfan** [comment]
> Hi @zqfan
> 
> There was no issue with my secretid and secret key. For my first implementation, it was running well. However, after several hours, I get errors when I run the code that is never changed by me. But, after several minutes, it is running well again without a change in my code
> 
> Thanks

Sounds like time zone issue, did it fail 100% when you get AuthFailure.SignatureFailure in that time period?

**Comment by microdevil** [comment]
> > Hi @zqfan
> > There was no issue with my secretid and secret key. For my first implementation, it was running well. However, after several hours, I get errors when I run the code that is never changed by me. But, after several minutes, it is running well again without a change in my code
> > Thanks
> 
> Sounds like time zone issue, did it fail 100% when you get AuthFailure.SignatureFailure in that time period?

Yes, it fail 100% when i get authfailure.
